#!/usr/bin/env python3
"""Guard: every dashboard Excel export separates deposit and withdraw slip lists."""
from __future__ import annotations

import importlib.util
import io
import os
import sys
import tempfile
import zipfile
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
os.environ["BOT_TOKEN"] = "TOKEN1"
os.environ["BOT_TOKEN_2"] = "TOKEN2"
os.environ["AUDITSLIP_TELEGRAM_BOTS"] = "bot1:BOT_TOKEN:บริษัท 1,bot2:BOT_TOKEN_2:บริษัท 2"
os.environ["AUDITSLIP_DB"] = str(Path(tempfile.mkdtemp(prefix="auditslip-export-flow-split-")) / "auditslip.db")
os.environ["AUDITSLIP_HOME"] = str(ROOT)
os.environ["AUDITSLIP_EXPORT_DIR"] = str(Path(tempfile.mkdtemp(prefix="auditslip-export-flow-split-out-")))
os.environ["AUDITSLIP_DASHBOARD_TOKEN"] = "test-token"

bot_spec = importlib.util.spec_from_file_location("auditslip_bot", ROOT / "auditslip_bot.py")
assert bot_spec and bot_spec.loader
bot_mod = importlib.util.module_from_spec(bot_spec)
sys.modules["auditslip_bot"] = bot_mod
bot_spec.loader.exec_module(bot_mod)

db_path = Path(os.environ["AUDITSLIP_DB"])
bot1 = bot_mod.AuditslipBot(token="TOKEN1", db_path=db_path, dry_run=True, bot_key="bot1", company_name="บริษัท 1")
bot2 = bot_mod.AuditslipBot(token="TOKEN2", db_path=db_path, dry_run=True, bot_key="bot2", company_name="บริษัท 2")
bot1.init_db(); bot2.init_db()
base = {
    "sender_name": "Uploader",
    "status": "success",
    "slip_date_display": "22/05/26",
    "slip_date_iso": "2026-05-22",
    "slip_time": "10:00",
    "transferor_name": "ลูกค้า",
    "recipient_name": "ร้านค้า",
    "from_bank": "KBANK",
    "to_bank": "SCB",
    "to_account": "SHARED-ACC-789",
    "amount": 100.0,
    "fee": 0.0,
}
bot1.save_slip({**base, "id": "DEP1", "bot_key": "bot1", "company_name": "บริษัท 1", "chat_id": "CHAT_DEP", "chat_title": "บริษัท 1 ฝาก/เติมมือ", "message_id": 101, "file_id": "FDEP", "amount": 111.0, "reference_no": "RDEP"})
bot1.save_slip({**base, "id": "WDR1", "bot_key": "bot1", "company_name": "บริษัท 1", "chat_id": "CHAT_WDR", "chat_title": "บริษัท 1 ถอน", "message_id": 102, "file_id": "FWDR", "from_account": "SHARED-ACC-789", "to_account": "DEST-WDR", "amount": 222.0, "reference_no": "RWDR"})
bot1.save_slip({**base, "id": "DUP1", "bot_key": "bot1", "company_name": "บริษัท 1", "chat_id": "CHAT_DEP", "chat_title": "บริษัท 1 ฝาก/เติมมือ", "message_id": 103, "file_id": "FDUP", "amount": 333.0, "reference_no": "RDUP", "is_duplicate": 1})
bot2.save_slip({**base, "id": "DEP2", "bot_key": "bot2", "company_name": "บริษัท 2", "chat_id": "CHAT2_DEP", "chat_title": "บริษัท 2 ฝาก", "message_id": 201, "file_id": "FDEP2", "amount": 444.0, "reference_no": "RDEP2"})
bot2.save_slip({**base, "id": "WDR2", "bot_key": "bot2", "company_name": "บริษัท 2", "chat_id": "CHAT2_WDR", "chat_title": "บริษัท 2 ถอน", "message_id": 202, "file_id": "FWDR2", "from_account": "SHARED-ACC-789", "to_account": "DEST-WDR2", "amount": 555.0, "reference_no": "RWDR2"})

spec = importlib.util.spec_from_file_location("auditslip_dashboard", ROOT / "auditslip_dashboard.py")
assert spec and spec.loader
Dash = importlib.util.module_from_spec(spec)
sys.modules["auditslip_dashboard"] = Dash
spec.loader.exec_module(Dash)


def records(ws):
    rows = list(ws.iter_rows(values_only=True))
    headers = list(rows[0])
    data = [dict(zip(headers, row)) for row in rows[1:]]
    # drop appended total row(s) — first column reads "รวม (...)"
    first = headers[0]
    data = [r for r in data if not str(r.get(first) or "").startswith("รวม")]
    return headers, data


# Normal workbook: keep the all-slips sheet, but also split operator item lists.
xlsx = Dash.export_dashboard_excel(db_path, bot_key="bot1", chat_id="", flow_type="all", scope="2026-05-22")
wb = load_workbook(xlsx, data_only=True)
assert {"Slips", "DepositSlips", "WithdrawSlips"}.issubset(set(wb.sheetnames)), wb.sheetnames
for sheet in ["Slips", "DepositSlips", "WithdrawSlips"]:
    headers, _ = records(wb[sheet])
    assert "id" not in headers and "bot_key" not in headers and "file_id" not in headers, (sheet, headers)
_, dep_records = records(wb["DepositSlips"])
_, wdr_records = records(wb["WithdrawSlips"])
assert [r["reference_no"] for r in dep_records] == ["RDEP"], dep_records
assert [r["reference_no"] for r in wdr_records] == ["RWDR"], wdr_records
assert "RDUP" not in [r["reference_no"] for r in dep_records + wdr_records]

# All-company ZIP workbooks are generated by the same export path and must carry split sheets too.
zip_path = Dash.export_dashboard_zip_by_company(db_path, bot_key="__all__", flow_type="all", scope="2026-05-22")
with zipfile.ZipFile(zip_path) as zf:
    bot1_name = next(name for name in zf.namelist() if "bot1" in name)
    bot1_wb = load_workbook(io.BytesIO(zf.read(bot1_name)), data_only=True)
assert {"DepositSlips", "WithdrawSlips"}.issubset(set(bot1_wb.sheetnames)), bot1_wb.sheetnames
_, zip_dep = records(bot1_wb["DepositSlips"])
_, zip_wdr = records(bot1_wb["WithdrawSlips"])
assert [r["reference_no"] for r in zip_dep] == ["RDEP"], zip_dep
assert [r["reference_no"] for r in zip_wdr] == ["RWDR"], zip_wdr

# Cross-company account export is also one Excel workbook with the same split sheets,
# but now in reconciliation layout (1 บรรทัด = 1 ยอด เทียบบริษัทซ้าย-ขวา).
cross_xlsx = Dash.export_cross_company_account_slips_excel(db_path, flow_type="all", scope="2026-05-22", search="SHAREDACC789")
cross_wb = load_workbook(cross_xlsx, data_only=True)
assert {"CrossCompanyAccountSlips", "DepositSlips", "WithdrawSlips"}.issubset(set(cross_wb.sheetnames)), cross_wb.sheetnames
_, cross_dep = records(cross_wb["DepositSlips"])
cross_wdr_headers, cross_wdr = records(cross_wb["WithdrawSlips"])
assert cross_dep == [], cross_dep
# RWDR(222 บริษัท 1) และ RWDR2(555 บริษัท 2) คนละยอด -> คนละบรรทัด แต่ละบรรทัดเฉพาะฝั่งเดียว
assert cross_wdr_headers[:2] == ["slip_date_display", "amount"], cross_wdr_headers
assert cross_wdr_headers[-4:] == ["companies_present", "match_status", "count_diff", "amount_diff"], cross_wdr_headers
by_amount = {float(r["amount"]): r for r in cross_wdr}
assert set(by_amount) == {222.0, 555.0}, cross_wdr
assert by_amount[222.0]["บริษัท 1 - อ้างอิง"] == "RWDR", cross_wdr
assert by_amount[555.0]["บริษัท 2 - อ้างอิง"] == "RWDR2", cross_wdr
assert all(r["match_status"] == "เฉพาะฝั่งเดียว" for r in cross_wdr), cross_wdr

print("ok: dashboard Excel exports separate deposit and withdraw slip sheets")
